### ISSUE TITLE
IIS 10

### ISSUE THREAD

**Issue by aslan2120** [stakach/IIS-X-Sendfile-plugin#5]
this may be a dumb question but is there a way to get this to work on IIS 10?

**Comment by stakach** [comment]
Probably not too hard. I don't really work with IIS anymore however happy to help out if I can.
Microsoft is pretty good with backwards compatibility too so I assume it would just work?

**Comment by aslan2120** [comment]
Well...   I am very new to iis so it might just be my lack of knowledge.   I was able to load the module but the instructions on how to add the directory I get lost. I cannot find "application settings".

**Comment by stakach** [comment]
![image](https://cloud.githubusercontent.com/assets/368013/17290892/0da14a66-5824-11e6-82fe-1dc7e3984fb6.png)

That's where you enter the settings

**Comment by aslan2120** [comment]
Oh geez...  I don't think I added the asp net when I added the iis components to Windows.  Thank you for the help.  I appreciate it.

**Comment by stakach** [comment]
Anytime
